name: Feature Request
description: Suggest a new feature or enhancement for the project.
labels: ["enhancement", triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com, github handle, etc.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please answer the following questions.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      placeholder: What is the feature you are proposing?
  - type: textarea
    id: motivation
    attributes:
      label: feature value
      placeholder: Why is this feature important?
